#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# CoATS Fabric Network — CA Enrollment & Identity Registration
# ═══════════════════════════════════════════════════════════════════════════════
#
# Enrolls CA admins, registers identities, and generates crypto material
# for the orderer and CoATS organizations using Fabric CA.
#
# This script is called by network.sh — not intended to be run standalone.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utils.sh
source "${SCRIPT_DIR}/utils.sh"

# ═══════════════════════════════════════════════════════════════════════════════
# NodeOUs Configuration Template
# ═══════════════════════════════════════════════════════════════════════════════

function writeNodeOUsConfig() {
  local MSP_DIR="$1"
  local CA_CERT_FILE="$2"

  cat > "${MSP_DIR}/config.yaml" <<EOF
NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/${CA_CERT_FILE}
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/${CA_CERT_FILE}
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/${CA_CERT_FILE}
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/${CA_CERT_FILE}
    OrganizationalUnitIdentifier: orderer
EOF
}

# ═══════════════════════════════════════════════════════════════════════════════
# Orderer Organization
# ═══════════════════════════════════════════════════════════════════════════════

function createOrdererOrg() {
  local CA_PORT="${CA_ORDERER_PORT:-7054}"
  local CA_NAME="ca-orderer"
  local ORG_DIR="${ORGANIZATIONS_DIR}/ordererOrg"
  local CA_DIR="${ORGANIZATIONS_DIR}/fabric-ca/ordererOrg"
  local CA_TLS_CERT="${CA_DIR}/tls-cert.pem"

  infoln "─── Creating Orderer Organization crypto material ───"

  # Wait for the CA TLS cert to exist (CA generates it on first start)
  local WAIT=0
  while [[ ! -f "${CA_TLS_CERT}" ]] && [[ $WAIT -lt 30 ]]; do
    sleep 1
    WAIT=$((WAIT + 1))
  done
  [[ -f "${CA_TLS_CERT}" ]] || fataln "Orderer CA TLS cert not found at ${CA_TLS_CERT}"

  mkdir -p "${ORG_DIR}"

  # ── 1. Enroll CA Admin ──────────────────────────────────────────────────
  infoln "Enrolling Orderer CA admin..."
  export FABRIC_CA_CLIENT_HOME="${ORG_DIR}"

  fabric-ca-client enroll \
    -u "https://${CA_ORDERER_ADMIN_USER}:${CA_ORDERER_ADMIN_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    --tls.certfiles "${CA_TLS_CERT}"

  # Determine the cacerts filename (auto-generated by fabric-ca-client)
  local CA_CERT_FILE
  CA_CERT_FILE="$(ls "${ORG_DIR}/msp/cacerts/" | head -1)"

  # ── 2. Write NodeOUs config to org MSP ──────────────────────────────────
  writeNodeOUsConfig "${ORG_DIR}/msp" "${CA_CERT_FILE}"

  # ── 3. Register Orderer Identity ────────────────────────────────────────
  infoln "Registering orderer identity..."
  fabric-ca-client register --caname "${CA_NAME}" \
    --id.name orderer --id.secret "${ORDERER_PASSWORD}" --id.type orderer \
    --tls.certfiles "${CA_TLS_CERT}"

  # ── 4. Register Orderer Admin Identity ──────────────────────────────────
  infoln "Registering orderer admin identity..."
  fabric-ca-client register --caname "${CA_NAME}" \
    --id.name ordererAdmin --id.secret "${ORDERER_ADMIN_PASSWORD}" --id.type admin \
    --tls.certfiles "${CA_TLS_CERT}"

  # ── 5. Enroll Orderer MSP ──────────────────────────────────────────────
  local ORDERER_DIR="${ORG_DIR}/orderers/orderer.coats.gov.in"
  infoln "Enrolling orderer MSP..."

  fabric-ca-client enroll \
    -u "https://orderer:${ORDERER_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${ORDERER_DIR}/msp" \
    --tls.certfiles "${CA_TLS_CERT}" \
    --csr.hosts "orderer.coats.gov.in,localhost,127.0.0.1,${EXTERNAL_HOST:-localhost}"

  cp "${ORG_DIR}/msp/config.yaml" "${ORDERER_DIR}/msp/config.yaml"

  # ── 6. Enroll Orderer TLS ──────────────────────────────────────────────
  infoln "Enrolling orderer TLS..."
  fabric-ca-client enroll \
    -u "https://orderer:${ORDERER_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${ORDERER_DIR}/tls" \
    --enrollment.profile tls \
    --tls.certfiles "${CA_TLS_CERT}" \
    --csr.hosts "orderer.coats.gov.in,localhost,127.0.0.1,${EXTERNAL_HOST:-localhost}"

  # Copy TLS files to standard names expected by Docker compose
  cp "${ORDERER_DIR}/tls/tlscacerts/"* "${ORDERER_DIR}/tls/ca.crt"
  cp "${ORDERER_DIR}/tls/signcerts/"*  "${ORDERER_DIR}/tls/server.crt"
  cp "${ORDERER_DIR}/tls/keystore/"*   "${ORDERER_DIR}/tls/server.key"

  # ── 7. Enroll Orderer Admin User ───────────────────────────────────────
  infoln "Enrolling orderer admin user..."
  fabric-ca-client enroll \
    -u "https://ordererAdmin:${ORDERER_ADMIN_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${ORG_DIR}/users/Admin@orderer.coats.gov.in/msp" \
    --tls.certfiles "${CA_TLS_CERT}"

  cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/users/Admin@orderer.coats.gov.in/msp/config.yaml"

  # ── 8. Build Org-level MSP ─────────────────────────────────────────────
  mkdir -p "${ORG_DIR}/msp/tlscacerts"
  cp "${ORDERER_DIR}/tls/ca.crt" "${ORG_DIR}/msp/tlscacerts/tls-ca.crt"

  successln "Orderer organization crypto material created."
}


# ═══════════════════════════════════════════════════════════════════════════════
# CoATS Organization
# ═══════════════════════════════════════════════════════════════════════════════

function createCoATSOrg() {
  local CA_PORT="${CA_COATS_PORT:-8054}"
  local CA_NAME="ca-coats"
  local ORG_DIR="${ORGANIZATIONS_DIR}/coatsOrg"
  local CA_DIR="${ORGANIZATIONS_DIR}/fabric-ca/coatsOrg"
  local CA_TLS_CERT="${CA_DIR}/tls-cert.pem"

  infoln "─── Creating CoATS Organization crypto material ───"

  # Wait for the CA TLS cert
  local WAIT=0
  while [[ ! -f "${CA_TLS_CERT}" ]] && [[ $WAIT -lt 30 ]]; do
    sleep 1
    WAIT=$((WAIT + 1))
  done
  [[ -f "${CA_TLS_CERT}" ]] || fataln "CoATS CA TLS cert not found at ${CA_TLS_CERT}"

  mkdir -p "${ORG_DIR}"

  # ── 1. Enroll CA Admin ──────────────────────────────────────────────────
  infoln "Enrolling CoATS CA admin..."
  export FABRIC_CA_CLIENT_HOME="${ORG_DIR}"

  fabric-ca-client enroll \
    -u "https://${CA_COATS_ADMIN_USER}:${CA_COATS_ADMIN_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    --tls.certfiles "${CA_TLS_CERT}"

  local CA_CERT_FILE
  CA_CERT_FILE="$(ls "${ORG_DIR}/msp/cacerts/" | head -1)"

  # ── 2. Write NodeOUs config ─────────────────────────────────────────────
  writeNodeOUsConfig "${ORG_DIR}/msp" "${CA_CERT_FILE}"

  # ── 3. Register Peer Identity ──────────────────────────────────────────
  infoln "Registering peer0 identity..."
  fabric-ca-client register --caname "${CA_NAME}" \
    --id.name peer0 --id.secret "${PEER0_PASSWORD}" --id.type peer \
    --tls.certfiles "${CA_TLS_CERT}"

  # ── 4. Register Org Admin Identity ─────────────────────────────────────
  infoln "Registering CoATS admin identity..."
  fabric-ca-client register --caname "${CA_NAME}" \
    --id.name coatsAdmin --id.secret "${COATS_ADMIN_PASSWORD}" --id.type admin \
    --tls.certfiles "${CA_TLS_CERT}"

  # ── 5. Register Client Identity (for Next.js app) ─────────────────────
  infoln "Registering CoATS client identity (for Next.js app)..."
  fabric-ca-client register --caname "${CA_NAME}" \
    --id.name coatsClient --id.secret "${COATS_CLIENT_PASSWORD}" --id.type client \
    --tls.certfiles "${CA_TLS_CERT}"

  # ── 6. Enroll Peer0 MSP ───────────────────────────────────────────────
  local PEER_DIR="${ORG_DIR}/peers/peer0.coats.gov.in"
  infoln "Enrolling peer0 MSP..."

  fabric-ca-client enroll \
    -u "https://peer0:${PEER0_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${PEER_DIR}/msp" \
    --tls.certfiles "${CA_TLS_CERT}" \
    --csr.hosts "peer0.coats.gov.in,localhost,127.0.0.1,${EXTERNAL_HOST:-localhost}"

  cp "${ORG_DIR}/msp/config.yaml" "${PEER_DIR}/msp/config.yaml"

  # ── 7. Enroll Peer0 TLS ───────────────────────────────────────────────
  infoln "Enrolling peer0 TLS..."
  fabric-ca-client enroll \
    -u "https://peer0:${PEER0_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${PEER_DIR}/tls" \
    --enrollment.profile tls \
    --tls.certfiles "${CA_TLS_CERT}" \
    --csr.hosts "peer0.coats.gov.in,localhost,127.0.0.1,${EXTERNAL_HOST:-localhost}"

  # Copy TLS files to standard names
  cp "${PEER_DIR}/tls/tlscacerts/"* "${PEER_DIR}/tls/ca.crt"
  cp "${PEER_DIR}/tls/signcerts/"*  "${PEER_DIR}/tls/server.crt"
  cp "${PEER_DIR}/tls/keystore/"*   "${PEER_DIR}/tls/server.key"

  # ── 8. Enroll Org Admin ───────────────────────────────────────────────
  infoln "Enrolling CoATS org admin..."
  fabric-ca-client enroll \
    -u "https://coatsAdmin:${COATS_ADMIN_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${ORG_DIR}/users/Admin@coats.gov.in/msp" \
    --tls.certfiles "${CA_TLS_CERT}"

  cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/users/Admin@coats.gov.in/msp/config.yaml"

  # ── 9. Enroll Client (Next.js app identity) ───────────────────────────
  infoln "Enrolling CoATS client for Next.js app..."
  fabric-ca-client enroll \
    -u "https://coatsClient:${COATS_CLIENT_PASSWORD}@localhost:${CA_PORT}" \
    --caname "${CA_NAME}" \
    -M "${ORG_DIR}/users/Client@coats.gov.in/msp" \
    --tls.certfiles "${CA_TLS_CERT}"

  cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/users/Client@coats.gov.in/msp/config.yaml"

  # ── 10. Build Org-level MSP ────────────────────────────────────────────
  mkdir -p "${ORG_DIR}/msp/tlscacerts"
  cp "${PEER_DIR}/tls/ca.crt" "${ORG_DIR}/msp/tlscacerts/tls-ca.crt"

  successln "CoATS organization crypto material created."
}


# ═══════════════════════════════════════════════════════════════════════════════
# Main (when called directly)
# ═══════════════════════════════════════════════════════════════════════════════

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  infoln "Starting CA enrollment process..."
  createOrdererOrg
  createCoATSOrg
  successln "All crypto material generated successfully."
fi
